# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'playground.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 560)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_back = QtWidgets.QPushButton(self.centralwidget)
        self.button_back.setGeometry(QtCore.QRect(10, 20, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.button_back.setFont(font)
        self.button_back.setStyleSheet("border-radius: 10;\n"
"background-color: rgb(180, 180, 180)")
        self.button_back.setObjectName("button_back")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(90, 90, 211, 79))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_score = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_score.setFont(font)
        self.label_score.setStyleSheet("border-radius: 10;\n"
"background-color: rgb(180, 180, 180)")
        self.label_score.setAlignment(QtCore.Qt.AlignCenter)
        self.label_score.setObjectName("label_score")
        self.verticalLayout.addWidget(self.label_score)
        self.score = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.score.setFont(font)
        self.score.setStyleSheet("border-radius: 10;\n"
"background-color: rgb(230, 230, 230)")
        self.score.setAlignment(QtCore.Qt.AlignCenter)
        self.score.setObjectName("score")
        self.verticalLayout.addWidget(self.score)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 210, 371, 341))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.data_grid = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.data_grid.setContentsMargins(0, 0, 0, 0)
        self.data_grid.setObjectName("data_grid")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_back.setText(_translate("MainWindow", "Back"))
        self.label_score.setText(_translate("MainWindow", "SCORE"))
        self.score.setText(_translate("MainWindow", "0"))
